#ifndef RESOURCE_H
#define RESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_LAUNCHER_BASE 500
#define IDD_LAUNCHER IDC_LAUNCHER_BASE
#define IDC_LIST_PROCESS (IDC_LAUNCHER_BASE + 1)
#define IDC_COMBO_GAME (IDC_LAUNCHER_BASE + 2)
#define IDC_RADIO_MODE_HOOK (IDC_LAUNCHER_BASE + 3)
#define IDC_RADIO_MODE_MORE (IDC_LAUNCHER_BASE + 4)
#define IDC_RADIO_SCALE_10 (IDC_LAUNCHER_BASE + 5)
#define IDC_RADIO_SCALE_15 (IDC_LAUNCHER_BASE + 6)
#define IDC_RADIO_SCALE_20 (IDC_LAUNCHER_BASE + 7)
#define IDC_RADIO_SCALE_AUTO (IDC_LAUNCHER_BASE + 8)

#define IDS_WARN_MISMATCH 2
#define IDS_WARN_INJECT 4
#define IDS_GAME_TITLE 6
#define IDS_TITLE_TH06 (IDS_GAME_TITLE + 0)
#define IDS_TITLE_TH07 (IDS_GAME_TITLE + 2)
#define IDS_TITLE_TH08 (IDS_GAME_TITLE + 4)
#define IDS_TITLE_TH09 (IDS_GAME_TITLE + 6)
#define IDS_TITLE_TH10 (IDS_GAME_TITLE + 8)
#define IDS_TITLE_TH11 (IDS_GAME_TITLE + 10)
#define IDS_TITLE_TH12 (IDS_GAME_TITLE + 12)
#define IDS_TITLE_TH13 (IDS_GAME_TITLE + 14)
#define IDS_TITLE_TH14 (IDS_GAME_TITLE + 16)
#define IDS_TITLE_TH15 (IDS_GAME_TITLE + 18)
#define IDS_TITLE_TH16 (IDS_GAME_TITLE + 20)
#define IDS_TITLE_TH17 (IDS_GAME_TITLE + 22)

#define IDT_REFRESH_PROC 1

#endif
